# Generated by Django 2.2.1 on 2020-03-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0004_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='user',
        ),
    ]
